name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull kush233/draw-websocket:latest
    - name: Delete Old docker container
      run: sudo docker rm -f draw-websocket-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name draw-websocket-container kush233/draw-websocket
 
